name: Verify terraform setup
on:
  push:
    branches-ignore:
      - main
    paths:
      - 'src/terraform/**'
  pull_request:
    branches: [ main ]

jobs:
  code-check:
    uses: ./.github/workflows/verifyTerraform.yml
    with:
      terraform-version: 1.1.7


